changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feat
    - title: Bug fixes
      labels:
        - fix
    - title: Refactors
      labels:
        - refactor
    - title: Docs
      labels:
        - doc
    - title: CI/CD
      labels:
        - ci
    - title: Test
      labels:
        - test
    - title: Others
      labels:
        - "*"
