on:
  workflow_dispatch:

name: Create Release 2

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Release
        uses: brpaz/action-semantic-release@v1
        
