on:
  workflow_dispatch:

name: Create Release 2

jobs:
  install-semantic-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Chekcout to repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
