name: Deploy Workflow

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    #if: github.event.pull_request.merged == true &&  contains(github.event.pull_request.head.ref,'release-please')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: List releases
      run: |
        echo releases
        IFS=' ' read -r -a array <<< gh release list -L 1
        echo "${array}"
   
