name: Deploy Workflow

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    #if: github.event.pull_request.merged == true &&  github.event.pull_request.head.ref == "**release**"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: List releases
      run: |
        echo The PR was merged
        echo -e "${github.event.pull_request.head.ref}"
        gh release list
  
