name: Release Workflow

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type": "feat", "section":"Features", "hidden": false},{"type": "fix", "section":"Bug Fixes", "hidden": false},{"type": "refactor", "section":"Refactors", "hidden": false},{"type": "docs", "section":"Documentation", "hidden": false}, {"type": "ci", "section":"CI/CD", "hidden": false},{"type": "perf", "section":"Performance", "hidden": false},{"type": "build", "section":"Build", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "style", "section":"Style", "hidden": false},{"type": "revert", "section":"Revert", "hidden": false}]'




